version: 0.2

phases:
  build:
    commands:
      - echo ================Build Stage================
artifacts:
  files:
     - aws_stack.yml
     - docker-compose.yml
     - appspec.yml
     - scripts/install_dependencies
     - scripts/start_server
     - scripts/stop_server
